import type { DesignDocument } from "../../design-ir/src/index.ts";

/** Lossless import for HTML generated by Roundtrip itself. */
export function importRoundtripHtml(html: string): DesignDocument {
  const m = html.match(/<script[^>]*id=["']roundtrip-designir["'][^>]*>([\s\S]*?)<\/script>/i);
  if (!m) throw new Error("No embedded Roundtrip DesignIR found. Generic HTML import is not implemented yet.");
  return JSON.parse(m[1].replaceAll("<\\/script", "</script")) as DesignDocument;
}

/**
 * Generic HTML -> DesignIR is intentionally a separate problem: computed CSS,
 * layout, web fonts, pseudo-elements and responsive behavior make it heuristic.
 */
export function importGenericHtml(_html: string): never {
  throw new Error("Generic HTML import is planned but not part of v0.2");
}
